-   id: fmt
    name: fmt
    description: Format files with rustfmt.
    entry: cargo fmt --
    language: system
    types: [rust]
    minimum_pre_commit_version: 1.10.0
-   id: cargo-check
    name: cargo check
    description: Check the package for errors.
    entry: cargo check
    language: system
    types: [rust]
    pass_filenames: false
    minimum_pre_commit_version: 1.10.0
-   id: clippy
    name: clippy
    description: Lint rust sources
    entry: cargo clippy -- -D warnings
    language: system
    types: [rust]
    pass_filenames: false
    minimum_pre_commit_version: 1.10.0
